[multi_instance]
enabled = true
default_instance = "instance0"

[instances.instance0]
name                   = "LDPlayer #0"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5555
emulator_profile_index = "0"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance0/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance1]
name                   = "LDPlayer #1"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5557
emulator_profile_index = "1"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance1/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance2]
name                   = "LDPlayer #2"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5559
emulator_profile_index = "2"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance2/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance3]
name                   = "LDPlayer #3"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5561
emulator_profile_index = "3"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance3/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance4]
name                   = "LDPlayer #4"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5563
emulator_profile_index = "4"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance4/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance5]
name                   = "LDPlayer #5"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5565
emulator_profile_index = "5"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance5/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance6]
name                   = "LDPlayer #6"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5567
emulator_profile_index = "6"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance6/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

[instances.instance7]
name                   = "LDPlayer #7"
enabled                = true
emulator               = "ldplayer"
emulator_port          = 5569
emulator_profile_index = "7"
player_tag             = "#YOURTAGHERE"
queue_path             = "instances/instance7/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""

# [instances.mumu0]
# name                   = "MuMu #0"
# enabled                = true
# emulator               = "mumu"
# emulator_port          = 16384
# emulator_profile_index = "0"
# player_tag             = "#YOURTAGHERE"
# queue_path             = "instances/mumu0/latest_brawler_data.json"
# discord_bot_token        = ""
# discord_channel_id       = ""
# discord_control_user_id  = ""
# discord_control_guild_id = ""
